myproject3/myproject3/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from myproject3 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myproject3app.urls'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)

myproject3/myproject3app/urls.py
from . import views
from django.urls import path
app_name = 'myproject3app'

urlpatterns = [
    path('', views.rest, name='restaurant'),
    path('viande/', views.viande, name='viande'),
]

myproject3/myproject3app/models.py
from django.db import models

# Create your models here.

myproject3/myproject3app/views.py
from django.shortcuts import render


# Create your views here.
def rest(request):
    return render(request, 'index.html')


def viande(request):
    return render(request, 'viande.html')

myproject3/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Savory Eats</title>
<meta name="description" content="">
<meta name="author" content="">

<!-- Favicons
    ================================================== -->
<link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">
<link rel="apple-touch-icon" href="img/apple-touch-icon.png">
<link rel="apple-touch-icon" sizes="72x72" href="img/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="114x114" href="img/apple-touch-icon-114x114.png">

<!-- Bootstrap -->
<link rel="stylesheet" type="text/css"  href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">

<!-- Stylesheet
    ================================================== -->
<link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
<link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Rochester" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
<!-- Navigation
    ==========================================-->
<nav id="menu" class="navbar navbar-default navbar-fixed-top">
  <div class="container"> 
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
    </div>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#features" class="page-scroll">Specials</a></li>
        <li><a href="#about" class="page-scroll">About</a></li>
        <li><a href="#restaurant-menu" class="page-scroll">Menu</a></li>
<!--        <li><a href="#team" class="page-scroll">Chef</a></li>-->
        <li><a href="#contact" class="page-scroll">Contact</a></li>
      </ul>
    </div>
    <!-- /.navbar-collapse --> 
  </div>
</nav>
<!-- Header -->
<header id="header">
  <div class="intro">
    <div class="overlay">
      <div class="container">
        <div class="row">
          <div class="intro-text">
            <h1>Savory Eats</h1>
            <p>Reservations: (+91) 9809227436</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Features Section -->
<div id="features" class="text-center">
  <div class="container">
    <div class="section-title">
      <h2>Our Specials</h2>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <div class="features-item">
          <h3>Viande</h3>
          <a href="{% url 'myproject3app:viande' %}"><img src="{% static 'img/specials/1.jpg' %}" class="img-responsive" alt=""></a>
          <p>Let us satisfy the connoisseur in you.</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="features-item">
          <h3>Pâtisserie</h3>
          <img src="{% static 'img/specials/2.jpg' %}" class="img-responsive" alt="">
          <p>Life is better with sprinkles on top.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- About Section -->
<div id="about">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-md-6 about-img"> </div>
      <div class="col-xs-12 col-md-3 col-md-offset-1">
        <div class="about-text">
          <div class="section-title">
            <h2>Our Story</h2>
          </div>
          <p>We strives to source local, sustainable and organic when possible. We work hard to source premium ingredients, and we cook everything from scratch with love.</p>
          <p>WE'RE NOT AFRAID TO FAIL, IT'S HOW WE ACHIEVE WHAT WE DO AS A TEAM AND WE HAVE A GOOD TIME DOING IT. WE LIKE TO CALL THIS 'SWAGGER.'</p>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Restaurant Menu Section -->
<div id="restaurant-menu">
  <div class="container">
    <div class="section-title text-center">
      <h2>Menu</h2>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <div class="menu-section">
          <h2 class="menu-section-title">Starters</h2>
          <div class="menu-item">
            <div class="menu-item-name">Chicken Cheese Roll</div>
            <div class="menu-item-price"> 260 </div>
            <div class="menu-item-description">  Roll Cheese Roll. </div>
          </div>
          <div class="menu-item">
            <div class="menu-item-name">Dragon Chicken</div>
            <div class="menu-item-price"> 250 </div>
            <div class="menu-item-description"> Made of tender chicken and not dragons. </div>
          </div>
          <div class="menu-item">
            <div class="menu-item-name">Crispy Chicken</div>
            <div class="menu-item-price"> 270 </div>
            <div class="menu-item-description"> Crunchy outside yummy inside. </div>
          </div>
          <div class="menu-item">
            <div class="menu-item-name">Fish Finger</div>
            <div class="menu-item-price"> 300 </div>
            <div class="menu-item-description"> Golden and crunchy tender fish </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="menu-section">
          <h2 class="menu-section-title">Viande</h2>
          <div class="menu-item">
            <div class="menu-item-name">Beef Steak</div>
            <div class="menu-item-price"> 450 </div>
            <div class="menu-item-description"> As long as there’s pink, we’re all good. </div>
          </div>
          <div class="menu-item">
            <div class="menu-item-name">Alfaham Mandhi</div>
            <div class="menu-item-price"> 190/360/700 </div>
            <div class="menu-item-description"> Love Yemeni </div>
          </div>
          <div class="menu-item">
            <div class="menu-item-name"> Turkish Platter Grill</div>
            <div class="menu-item-price"> 2400 </div>
            <div class="menu-item-description"> Perfect Turkish taste for entire family. Sharing is caring. </div>
          </div>
          <div class="menu-item">
            <div class="menu-item-name">Biriyani</div>
            <div class="menu-item-price"> C/B-160/140 </div>
            <div class="menu-item-description"> Need good sleep, have a biriyani pill. </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <div class="menu-section">
          <h2 class="menu-section-title">Pâtisserie</h2>
          <div class="menu-item">
            <div class="menu-item-name">Jar Cake</div>
            <div class="menu-item-price"> 100 </div>
            <div class="menu-item-description"> Juicy Cake. </div>
          </div>
          <div class="menu-item">
            <div class="menu-item-name">Cheese Kunafa</div>
            <div class="menu-item-price"> 400 </div>
            <div class="menu-item-description"> Kunafa with extra cheesy for cheesy people. </div>
          </div>
          <div class="menu-item">
            <div class="menu-item-name">Death by Chocolate</div>
            <div class="menu-item-price"> 900 </div>
            <div class="menu-item-description"> Chocolate lover perfect lover. </div>
          </div>
          <div class="menu-item">
            <div class="menu-item-name">Kitorela Cake</div>
            <div class="menu-item-price"> 1250 </div>
            <div class="menu-item-description"> Love triangle-KITie OREie NUTie. </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="menu-section">
          <h2 class="menu-section-title">Boissons</h2>
          <div class="menu-item">
            <div class="menu-item-name">Floating Island</div>
            <div class="menu-item-price"> 100 </div>
            <div class="menu-item-description"> Floating toungue. </div>
          </div>
          <div class="menu-item">
            <div class="menu-item-name">Chocolate Shake</div>
            <div class="menu-item-price"> 110 </div>
            <div class="menu-item-description"> Drink your chocolate like a cat. </div>
          </div>
          <div class="menu-item">
            <div class="menu-item-name">Black Beauty</div>
            <div class="menu-item-price"> 130 </div>
            <div class="menu-item-description"> Black is love. </div>
          </div>
          <div class="menu-item">
            <div class="menu-item-name">Retro Delight</div>
            <div class="menu-item-price"> 160 </div>
            <div class="menu-item-description"> End your day delightedly. </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Gallery Section -->
<div id="gallery">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-6 col-md-3">
        <div class="gallery-item"> <img src="{% static 'img/gallery/01.jpg' %}" class="img-responsive" alt=""></div>
      </div>
      <div class="col-xs-6 col-md-3">
        <div class="gallery-item"> <img src="{% static 'img/gallery/02.jpg' %}" class="img-responsive" alt=""></div>
      </div>
      <div class="col-xs-6 col-md-3">
        <div class="gallery-item"> <img src="{% static 'img/gallery/03.jpg' %}" class="img-responsive" alt=""></div>
      </div>
      <div class="col-xs-6 col-md-3">
        <div class="gallery-item"> <img src="{% static 'img/gallery/04.jpg' %}" class="img-responsive" alt=""></div>
      </div>
    </div>
  </div>
</div>

<!-- Contact Section -->
<div id="contact" class="text-center">
  <div class="container text-center">
    <div class="col-md-6">
      <h3>Reservations</h3>
      <div class="contact-item">
        <p>Please call</p>
        <p>(+91) 9809227436</p>
      </div>
    </div>
<!--    <div class="col-md-4">-->
<!--      <h3>Address</h3>-->
<!--      <div class="contact-item">-->
<!--        <p>4321 California St,</p>-->
<!--        <p>San Francisco, CA 12345</p>-->
<!--      </div>-->
<!--    </div>-->
    <div class="col-md-6">
      <h3>Opening Hours</h3>
      <div class="contact-item">
        <p>Mon-Thurs: 10:00 AM - 11:00 PM</p>
        <p>Fri-Sun: 11:00 AM - 02:00 AM</p>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="section-title text-center">
      <h3>Send us a message</h3>
    </div>
    <div class="col-md-8 col-md-offset-2">
      <form name="sentMessage" id="contactForm" novalidate>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <input type="text" id="name" class="form-control" placeholder="Name" required="required">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <input type="email" id="email" class="form-control" placeholder="Email" required="required">
              <p class="help-block text-danger"></p>
            </div>
          </div>
        </div>
        <div class="form-group">
          <textarea name="message" id="message" class="form-control" rows="4" placeholder="Message" required></textarea>
          <p class="help-block text-danger"></p>
        </div>
        <div id="success"></div>
        <button type="submit" class="btn btn-custom btn-lg">Send Message</button>
      </form>
    </div>
  </div>
</div>
<div id="footer">
  <div class="container text-center">
    <div class="col-md-6">
      <p>&copy; AMJ tech pvt ltd. All rights Reserved</p>
    </div>
    <div class="col-md-6">
      <div class="social">
        <ul>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-youtube"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript" src="{% static 'js/jquery.1.11.1.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/SmoothScroll.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jqBootstrapValidation.js' %}"></script>
<script type="text/javascript" src="{% static 'js/contact_me.js' %}"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</body>
</html>

myproject3/templates/viande.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>viande</title>
</head>
<body>
<div class="container">
    <div class="row mx-auto">
        <div class="col-sm-4" style="margin-bottom:25px;">
            <div class="shadow card text-center" style="width:18rem; height:22rem;">
            <div class="card-body">
                <h4><b>steak</b></h4>
                <p>Rs.1500</p>
            </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>